# Generated by Django 4.2.11 on 2024-05-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish']},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-publish'], name='app_post_publish_16e00e_idx'),
        ),
    ]
